version: "3.7"
services:
  backend:
    build: .
    ports:
      - "8181:8181"
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=barber_shop
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - "5432:5432"
volumes:
  db-data:
networks:
  spring-postgres: